### ISSUE TITLE
Syntax issue with python script

### ISSUE THREAD

**Issue by PHlightroom** [astuder/lightroom-map-fix#1]
Trying to use the patchluastr.py script and getting a syntax error "unexpected character after line continuation character"
Is this a script error or user error on my part ?
The script is all one line.
![python-syntax-failure](https://user-images.githubusercontent.com/46166512/50452568-abfcd880-0932-11e9-94ab-b7b31d3bb275.jpg)

On Windows 7 64bt

**Comment by PHlightroom** [comment]
Thanks for the fast reply.
I'm still not getting something right.
I've tried putting the patchluastr.py in the python directory, but still getting an error.
![python-error-4](https://user-images.githubusercontent.com/46166512/50459255-702d3780-0961-11e9-9ed1-58e63aa41c7c.jpg)

**Comment by astuder** [comment]
You have to download the Python script patchluastr.py from Github, e.g. by downloading the whole repository as ZIP file.
https://github.com/astuder/lightroom-map-fix/archive/master.zip

I recently also added a ZIP file with the Python script as an executable, but not sure if that works on across all Windows versions.
https://github.com/astuder/lightroom-map-fix/blob/master/patchluastr-win10.zip

**Comment by PHlightroom** [comment]
Thanks again Adrian for your help on this.
Yes, I'm using the script in the zip file and I've read everything several times now.
The errors seem to be due to either file naming, file location or CLI syntax to python.
For someone that's not a previous user of Python it's all a bit of a nightmare. Everything else in the document seems very easy to understand and act on, but Python's CLI isn't so easy.
Exactly where should the script (patchluastr.py) sit in the directory structure ?
I've used all the default installation options in Python on W7 64.
At the moment I'm trying to hack the Location.lrmodule file in a separate directory (E:/LR/), that also contains the two *.lua components pulled out by Resource Hacker, to avoid damaging my working LR installation.  When the python script has worked I'll copy it across to the working directory on C:

**Comment by astuder** [comment]
The error message above indicares that patchluastr.py is not in the current location. Simply prefix it with path where you unpacked patchlustr.py.

**Comment by astuder** [comment]
E.g. 
python \downloadpath\master\patchluastr.py ...

**Comment by astuder** [comment]
Or copy the script to your working folder

**Comment by PHlightroom** [comment]
I've moved the script and the *.lua files into the Python directory, but am still getting an 'invalid syntax' error when running the script.
It looks like an error with the output syntax ?? Something is missing I assume.
![python-errort1](https://user-images.githubusercontent.com/46166512/50475491-ee6af780-09bc-11e9-8ac4-6e28d44a6fb0.jpg)

**Comment by PHlightroom** [comment]
Thanks for your help on this;
The key issue seems to be working in a full command prompt opened by typing win key and r 
I've now got the script to work, followed the rest of the instructions without problem and the map module works nearly as expected other than an error message “Map Error : request denied” that flashes up on loading and when moving the map. However the message doesn't seem to cause any other issues and geo-tagging and displays seem to work as expected.
![map-error](https://user-images.githubusercontent.com/46166512/50488626-593b2380-09fb-11e9-9401-c65a8aa425d3.jpg)
Thanks for your work on this you're a hero :-)
