### ISSUE TITLE
little issue with readme instructions

### ISSUE THREAD

**Issue by MK-19** [astuder/lightroom-map-fix#13]
Hi Adrian, you are a hero and saved my day, really cool that you got that running again!!!

I worked me through the process today with LR 6.14 on WIN 10, worked smoothly with one exception: The python script did initially not work properly. The order of arguments is currently wrong in the readme section. Could you please fix the readme section for the ones to follow?

This is how it worked:
patchluastr.py -o AGREVERSEGEOCODESERVICE.bin AGREVERSEGEOCODESERVICE.LUA "client=gme-adobesystems" "key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

Thanks again - Martin

**Comment by astuder** [comment]
Can't reproduce issue with order of parameters.
