### ISSUE TITLE
Please add to readme - fix for reverse geocoding

### ISSUE THREAD

**Issue by MK-19** [astuder/lightroom-map-fix#14]
Hi Adrian,

I would propose to add the following section to the Readme as well (full credits go to evanwarner for the Issue Report "Address Lookup doesn't work with fix?"). Following this I was able to fix my reverse geo coding completely by applying another LUA replace.

Would propose to add this to the readme section as well.

patchluastr.py -o LOCATIONDEBUGPANEL.bin LOCATIONDEBUGPANEL.LUA "nature" "xyz"

Thanks - Martin

**Comment by AndreasTheNavigator** [comment]
Hi,
applying only the patches to exchange the ID didn't do the trick for me (100% error 403). Had to make this change as well. Now works like a charm. Thanks so much!

**Comment by astuder** [comment]
Thanks for reporting back @AndreasTheNavigator 

Not sure why there's a difference between different installations of Lightroom 6.

**Comment by astuder** [comment]
Updated readme to include updating LocationDebugPanel
