### ISSUE TITLE
LocationDebugPanel.lua -> nothing to patch

### ISSUE THREAD

**Issue by cyr06** [astuder/lightroom-map-fix#15]
Hi 
first I thank you for trying help us getting our software back !!
My config : OSX 10.14.3 / LR 6.14
I followed the readme instructions and I get 2 patched files but 1 doesn't 
Processing LocationMapView.lua -> Updated 2 strings 👍 
Processing AgReverseGeocodeService.lua -> Updated 1 strings 👍 
Processing LocationDebugPanel.lua -> 'client=gme-adobesystems' not found, nothing to patch 👎 
as a result the module is still broken
Hope you have an idea for me.
Thank you again
Cyril

**Comment by astuder** [comment]
Oops, copy pasta error in the description for Mac.

The correct patching command for LocationDebugPanel.lua should be:
```
patchluastr.py LocationDebugPanel.lua "nature" "street" -o LocationDebugPanel-patched.lua
```

Though, the basics of the map module should work even without patch of LocationDebugPanel.

**Comment by cyr06** [comment]
indeed 
Processing LocationDebugPanel.lua -> Updated 1 strings
unfortunately map module isn't working better
I didn't have google account before following instructions, maybe it takes time to activate ?

**Comment by astuder** [comment]
Google account should work immediately. 

Make sure to copy the complete API key. And only the API key without characters before and after. No curly brackets etc.

On the Google dashboard, you should see hits from the API access a few minutes after using Lightroom.

**Comment by cyr06** [comment]
I feel so stupid
I used "key={xxxxxxx}" instead of "key=xxxxxxxx"
without brackets the map loads !!
thank you very much for your support and sorry for my misunderstanding 
Have a good day

**Comment by astuder** [comment]
No worries. I will try to clarify the documentation.
