### ISSUE TITLE
patchluastr.py

### ISSUE THREAD

**Issue by Numb-nut** [astuder/lightroom-map-fix#18]
Don't know if I'm being thick but I've installed Python 3.7 on mac os. In a Terminal window i can not get patchluastr.py to work to change the key on LocationMapView.
Any advice would be appreciated.

**Comment by astuder** [comment]
Any error messages?

**Comment by Numb-nut** [comment]
Thanks for your response Adrian. 
No, I’m not getting any error messages. 
I’ve tried moving copies of the files into the Python3 directory and running patchluastr.py from there and the only response I have had is a “syntax error” and shows as Location, I have tried using upper and lower case of the “L” but I don’t seem to be getting anywhere with it. 
I have downloaded python3 three times over the last couple of months and been trying to do this without any joy. 
On my first attempt I followed the instructions and set up my key codes. But the last couple of sessions I’ve just been trying to change the files using key 1234 or something similar. 
Not sure if any of this helps, I may just have to give up with this, a shame I know but it’s doing my head in. 

Paul

**Comment by astuder** [comment]
Double-check that the patchluastr.py was downloaded correctly. You can open it in a text editor and check if the first few lines are the same as in GitHub.

The easiest is, to download the whole project as ZIP file:
https://github.com/astuder/lightroom-map-fix/archive/master.zip

**Comment by Numb-nut** [comment]
Thanks Adrian I’ll give it another go.

Your help is much appreciated.

Paul
