### ISSUE TITLE
Was working but no longer...

### ISSUE THREAD

**Issue by truculent-llama** [astuder/lightroom-map-fix#19]
First of all, thanks for the great write up and the workaround.
When I found this I was overjoyed that finally my map was working again in LR6, having followed your instructions and getting it all sorted.
I haven't used it in some time however and now that I'm trying to use it again, it seems to be broken... but I don't know why. So I went back, redid all the steps on my originally backed up lrmodule file, but still nothing. 
I even generated a new API key in the hopes that something had gone awry there, and redid all the steps again, but still to no avail.

I'm not getting any errors when running patchluastr.py and it's doing what it's supposed to. Everything is going the say way it did the first time I ran through it.

Then I load up LR and it does that thing where the map appears for a split second, then I get the error that the map didn't load correctly and to see the JavaScript console for technical details.
I've checked my Google cloud and there aren't even any requests coming in for my API.
I've checked my LR version and it's still at 6.14, so thankfully hasn't just updated itself.

P.S. wasn't sure if this belongs in "issues" but thought maybe something had changed that may affect others also.

Would appreciate any suggestions.
Many thanks,
Llama

**Comment by astuder** [comment]
Thank you for reporting the issue.

It still works for me, but there are others that had to make additional changes to get the maps working. I wonder if Google starts phasing out certain APIs depending on your country.

Can you get maps working by patching the API address maps.google.com as described here?
https://github.com/astuder/lightroom-map-fix/issues/12#issuecomment-499776944

**Comment by truculent-llama** [comment]
Adrian, thank you for your prompt reply and for pointing me in the right direction.
After reading through all the posts in issue #12 I've managed to get the maps working again by following the full process as outlined by wagnerralf:

- [ ] patchluastr.py LOCATIONMAPVIEW.LUA "client=gme-adobesystems_TESTING_INVALID" "key=myAPI" -o LOCATIONMAPVIEW.1
- [ ] patchluastr.py LOCATIONMAPVIEW.1 "client=gme-adobesystems" "key=myAPI" -o LOCATIONMAPVIEW.2
- [ ] patchluastr.py LOCATIONMAPVIEW.2 "maps.google.com" "maps.googleapis.com" -o LOCATIONMAPVIEW.bin
- [ ] patchluastr.py AGREVERSEGEOCODESERVICE.LUA "client=gme-adobesystems" "key=myAPI" -o AGREVERSEGEOCODESERVICE.bin
- [ ] patchluastr.py LOCATIONDEBUGPANEL.LUA "nature" "street" -o LOCATIONDEBUGPANEL.bin

I've checked on my Google Cloud dashboard and my API is properly getting requests now.
To make the process a little easier for myself I created a quick Windows batch file to run all the changes in one easy go.

Thanks for your help again and for your awesome work on this.

**Comment by astuder** [comment]
Thank you for reporting back. Creating a batch file is actually a good idea.

**Comment by Freneato** [comment]
> 
> 
> Adrian, thank you for your prompt reply and for pointing me in the right direction.
> After reading through all the posts in issue #12 I've managed to get the maps working again by following the full process as outlined by wagnerralf:
> 
>     * patchluastr.py LOCATIONMAPVIEW.LUA "client=gme-adobesystems_TESTING_INVALID" "key=myAPI" -o LOCATIONMAPVIEW.1
> 
>     * patchluastr.py LOCATIONMAPVIEW.1 "client=gme-adobesystems" "key=myAPI" -o LOCATIONMAPVIEW.2
> 
>     * patchluastr.py LOCATIONMAPVIEW.2 "maps.google.com" "maps.googleapis.com" -o LOCATIONMAPVIEW.bin
> 
>     * patchluastr.py AGREVERSEGEOCODESERVICE.LUA "client=gme-adobesystems" "key=myAPI" -o AGREVERSEGEOCODESERVICE.bin
> 
>     * patchluastr.py LOCATIONDEBUGPANEL.LUA "nature" "street" -o LOCATIONDEBUGPANEL.bin
> 
> 
> I've checked on my Google Cloud dashboard and my API is properly getting requests now.
> To make the process a little easier for myself I created a quick Windows batch file to run all the changes in one easy go.
> 
> Thanks for your help again and for your awesome work on this.

This new solution worked for me as well in germany. I was wondering, because on the first attempt erverything was fine. On the other day it stopped working. I had to move "maps.google.com" to "maps.googleapis.com"
