### ISSUE TITLE
?:0) attempt to index a boolean value

### ISSUE THREAD

**Issue by keithdw1973** [astuder/lightroom-map-fix#20]
I am a complete noob to this, so followed the instructions to the letter (I think).

I extracted the three .LUA files from the Location.lrmodule file and using the patchluastr.exe file in Windows 10, had the following positive messages (I've replaced most of my API Key with ????.

```
\Lightroom Map Fix>patchluastr.exe LOCATIONMAPVIEW.LUA "client=gme-adobesystems" "key=AI???????????????????????????????p_wes" -o LOCATIONMAPVIEW.bin
Processing LOCATIONMAPVIEW.LUA
Lua 5.1 detected
Lua settings: endian 1, int 4, size_t 8, instruction 4, number 4
119454 bytes read from file
Found 'client=gme-adobesystems' at 10424
Found 'client=gme-adobesystems' at 21086
Updated 2 strings
119494 bytes written to LOCATIONMAPVIEW.bin

\Lightroom Map Fix>patchluastr.exe AGREVERSEGEOCODESERVICE.LUA "client=gme-adobesystems" "key=AI???????????????????????????????p_wes" -o AGREVERSEGEOCODESERVICE.bin
Processing AGREVERSEGEOCODESERVICE.LUA
Lua 5.1 detected
Lua settings: endian 1, int 4, size_t 8, instruction 4, number 4
10715 bytes read from file
Found 'client=gme-adobesystems' at 1601
Updated 1 strings
10735 bytes written to AGREVERSEGEOCODESERVICE.bin

\Lightroom Map Fix>patchluastr.exe LOCATIONDEBUGPANEL.LUA "nature" "street" -o LOCATIONDEBUGPANEL.bin
Processing LOCATIONDEBUGPANEL.LUA
Lua 5.1 detected
Lua settings: endian 1, int 4, size_t 8, instruction 4, number 4
11590 bytes read from file
Found 'nature' at 11464
Updated 1 strings
11590 bytes written to LOCATIONDEBUGPANEL.bin
```
I then re-inserted the .bin files into the Location.lrmodule file (original size 1232KB, patched 921KB).

This was then copied back into the Lightroom install folder - so far so good!

Lightroom loaded correctly, but when I click on the map tab on the menu I get an error message 
?:0) attempt to index a boolean value
![image](https://user-images.githubusercontent.com/40072536/62488530-6358a800-b7bc-11e9-825c-b121f783eb42.png)

I am running Lightroom CC 2015.14 Release - I'm not sure what version number that is!
![image](https://user-images.githubusercontent.com/40072536/62488614-97cc6400-b7bc-11e9-96bb-2ebb24a93c7b.png)

Thanks for your efforts, I hope this is something I'm doing wrong, missing.

**Comment by astuder** [comment]
I don't have Lightroom CC, so I don't know if this patch also works for that version.

Does you API key contain special characters? Mine only contains letters and numbers.

**Comment by keithdw1973** [comment]
My API key does contain an underscore, yes!
![image](https://user-images.githubusercontent.com/40072536/62553779-dc610980-b867-11e9-83bf-1a9fd31f5479.png)

I used the copy feature when generating the key to ensure no typos!
![image](https://user-images.githubusercontent.com/40072536/62553917-1b8f5a80-b868-11e9-8122-d9364e45fe14.png)

On my dashboard, it seems to show things are getting through, but why there are 90% error and not 100% I have no idea.
![image](https://user-images.githubusercontent.com/40072536/62554015-4d082600-b868-11e9-95c8-479c1ec40da1.png)

Anyway, I think I have an old copy of LM6 somewhere in my archive, I've dig it out and try with that.

**Comment by astuder** [comment]
Underscore shouldn't be an issue. I was more worried about & and ?, which would require some HTTP escaping. But as the requests show up in your console, the patching of the API key is very likely working.

I'm not very familiar with the Google cloud, but if it's possible to drill down into the errors or find a log we may have more clues on what goes wrong.

**Comment by astuder** [comment]
PS: If you send me the unpatched .LUA files to the email address on my GitHub profile I can verify that the patching works as expected.

**Comment by keithdw1973** [comment]
Sure thing astuder, I will send you the .lua files.

I found out that the installer from Adobe for Lightroom 6 and CC 2015 are the same, and only change branding upon registration with Adobe!

> The brand new Lightroom free trial download always starts off as Lightroom CC, but after installation it can be converted to Lightroom 6 if that’s what you decide to buy instead… After you make the standalone purchase, the product branding will transform to Lightroom 6

[https://prodesigntools.com/differences-between-lightroom-6-cc-vs-5.html](url)

I think, also there may be a problem with my Google API account, which Google are investigating. It seems the billing is not setup correctly, although all the details are correct! So it is only allowing 1 API hit per day. So, I'll wait to see what they say about that.

**Comment by keithdw1973** [comment]
Had a response from Google and they fixed my console.cloud.google.com account. Everything seems to be working as expected now. So the issue was on googles side.

Thanks for your efforts, and thanks for the Lightroom fix.
