### ISSUE TITLE
Lightroom 6.14 : Map not working

### ISSUE THREAD

**Issue by sebsebseb1982** [astuder/lightroom-map-fix#21]
Hi !

I've modified my Location.lrmodule as explained [here](https://github.com/astuder/lightroom-map-fix/issues/19#issuecomment-502568837), but it is still not working :-(

![files](https://user-images.githubusercontent.com/3707818/63686266-bfce4680-c801-11e9-8939-bd8ed46ade91.png)
![lightroomError](https://user-images.githubusercontent.com/3707818/63686267-bfce4680-c801-11e9-893a-4bf66a25476b.png)
![patchLUA](https://user-images.githubusercontent.com/3707818/63686268-c066dd00-c801-11e9-9329-5736e1b6f561.png)

Do you know where I can find logs that could help me ?

Thank you,
Sébastien

**Comment by sebsebseb1982** [comment]
Hi, thank you for your answer !
I don't see any traffic in my Google Cloud Account.

Can you confirm me that the key to use is this one :

![key](https://user-images.githubusercontent.com/3707818/63705007-89f28780-c82c-11e9-8c24-0e38d12acd6a.png)

I've got theses API activated : 

![apis](https://user-images.githubusercontent.com/3707818/63705137-d6d65e00-c82c-11e9-98c1-42a98cad5f2b.png)

If you can confirm that everything seems OK, I'll will try to regenerate my key and patch again the module.

**Comment by sebsebseb1982** [comment]
I've regenerate my key which now does nto contains hyphen (the first one was). Still not working.
My key contains only alphanumerical chars now.
Lightroom was closed during process. 
I've tried to rename `Location.lrmodule` --> `Location.lrmodule.bak`. Map module is still bugged and this is the same error (it does not ask for `Location.lrmodule.bak` explicitly).

**Comment by sebsebseb1982** [comment]
I've checked hexa content and replace seems to be done :-\

**Comment by sebsebseb1982** [comment]
With original or without any Location.lrmodule, I've got the same error as the one in my first comment. I' ve not find any log or debug mode/console ...
Could I sent you my modified module ?

**Comment by timbothegreat3** [comment]
I had heaps of trouble getting this working.  My top is that modifying the
file is pretty straight forward with clear instructions. I missed some of
the things in the google end of things which made mine work straight away
after fixing,

**Comment by sebsebseb1982** [comment]
My Google API seems to be OK. I'll try to find someone who can test my module

**Comment by Sventheviking** [comment]
Hello,
I performed all the steps, including changing the URL but unfortunately it still does not work.
Using a very simple test page I was able to validate my api key so that's not the issue.

Is there a way to turn on the location debug panel or otherwise see which calls ligthroom makes ?

**Comment by astuder** [comment]
Sorry, but I really can't reproduce those issues. Are any of you using non-english versions of LR?

Unfortunately, I haven't figured out how to enable the debug console that the error message mentions. I suspect it's a standard message from the embedded browser that displays the map.

**Comment by sebsebseb1982** [comment]
Hi Astruder,

I don't know if it is a specific version, but mine is translated in french. 

![image](https://user-images.githubusercontent.com/3707818/67138350-1c6a4280-f242-11e9-86b0-a0367c2c8823.png)

If you want, I can send you my Location.lrmodule to test (I will invalidate my API key later).

**Comment by Sventheviking** [comment]
I'm using it in French as well but doubt Adobe made language specific versions.
Anyway I switched to English in Preferences and the error is still there.

Do you know how to trace all the http calls and responses ? I'll do some research on my side, just wondering if you alredy did it.

**Comment by sebsebseb1982** [comment]
Nope. I haven't time to do it now but maybe [Fiddler](https://www.telerik.com/fiddler) (if it's still compatible with Windows 10) could bring answers.

**Comment by Sventheviking** [comment]
Something really weird happened that I absolutely cannot explain...

- Installed Fiddler and took a trace with the modified location.lrmodule
- No errors, it loaded a bunch of map elements from the last location I visited and then the circled exclamation mark. At no time I saw any of the queries modified.
- Put the original location.lrmodule in place to get a comparison
- Everything just worked perfectly, fully functional map module and I clearly saw it using my API key in all queries

I went back to resource hacker to check location.lrmodule and it definitely is the original... I have absolutely no clue which file LR is using but the fact is that it somehow switched to my API key.
Maybe it cached data from the modified file somewhere and just decided to use it.

**Comment by astuder** [comment]
Someone just posted this on the thread in DPreview:

> IMPORTANT NOTE: Windows 10, I had a lot of trouble and tried 3 times, despite having Google API experience. The problem was, I didn't remove the backup file from the original directory (and it still had the same .lrmodule extension). Even though it had an obviously different filename, it was still getting picked up by LR instead of my patched file. Either change the extension of the backup file, or move it. I hope this helps someone else!

Please let me know if this solves the mystery for any of you.

**Comment by sebsebseb1982** [comment]
Yes ! that's it !

**Comment by Sventheviking** [comment]
Same for me ! Changing the extension did it.

Thanks a lot.
