### ISSUE TITLE
MacOS not able to run the command in terminal

### ISSUE THREAD

**Issue by Delfinder** [astuder/lightroom-map-fix#23]
I am stuck with running the commands. I open terminal change into the directory where the 3 lightroom lua files and patchluastr.py are located.
Do I need to change something in the Python launcher window?

This is what Terminal does:
_Names-iMac:desktop name$ cd patch
Names-iMac:patch name$ patchluastr.py LocationMapView.lua.bak "client=gme-adobesystems" "key=google API-key" -o LocationMapView.lua
-bash: patchluastr.py: command not found
Names-iMac:patch name$ patchluastr.py LocationMapView.lua.bak "client=gme-adobesystems" "key=google API-key" -o LocationMapView.lua
-bash: patchluastr.py: command not found_

How do I run this script? I am lost between python and running the command line.

Thank you all guys for your great work helping people not to waste more money on Adobe!

![Untitled](https://user-images.githubusercontent.com/18385567/67248750-ae30a600-f422-11e9-85be-cedd8b5ec78c.png)

**Comment by astuder** [comment]
You can try to add python before patchluastr.py:
> python luapatchstr.py ....

However, if you are not familiar with using command line tools, I strongly recommend you find someone locally to help you. It's not rocket science, but it's quite easy to ruin you installation of LR if you don't know what you are doing.

**Comment by Delfinder** [comment]
Thank you astuder for your quick response. I appreciate your warning and I understand it. I am not a coder but more than 30 years into computers, so I know what to do when I screw up things - hopefully :-)

After changing it is performing the script but it returns this error message (for all 3 files):

usage: patchluastr.py [-h] [-o OUTPUT] [-s] input find replace
patchluastr.py: error: argument input: can't open 'LocationMapView.lua.bak': [Errno 2] No such file or directory: 'LocationMapView.lua.bak'
TypeError: unsupported operand type(s) for >>: 'str' and 'int'_

File names should be correct
![Untitled](https://user-images.githubusercontent.com/18385567/67302419-17a9c680-f4ae-11e9-8883-e09ae24e2574.png)

**Comment by astuder** [comment]
Verify that you have Python 3 installed. `python -V` will output the version. If it says 2.x, try the command `python3` instead.

**Comment by Delfinder** [comment]
Thank you for responding so quickly. I have Python Launcher 3.8 but in the system it is still 2.7.10. Installing a later version seems to be quite a bit complicated as a quick research returned. Do you have any recommendation? I am not sure if I can find someone where I am living (rural Canada) who can work on MacOS

**Comment by Delfinder** [comment]
Another check returned that:
Franks-iMac:~ frank$ python -V
Python 2.7.10
Name-iMac:~ name$ python3 --version
Python 3.8.0
Name-iMac:~ name$

**Comment by astuder** [comment]
In that case, try prefixing the command line with python3. E.g. `python3 patchluastr.py ...`

**Comment by Delfinder** [comment]
I did and still returns the same error

_usage: patchluastr.py [-h] [-o OUTPUT] [-s] input find replace
patchluastr.py: error: argument input: can't open 'LocationMapView.lua.bak': [Errno 2] No such file or directory: 'LocationMapView.lua.bak'_

**Comment by Delfinder** [comment]
Command line is:
python3 patchluastr.py LocationMapView.lua.bak "client=gme-adobesystems" "key=xxxxxx" -o LocationMapView.lua

**Comment by astuder** [comment]
what does `ls` return?

**Comment by Delfinder** [comment]
AgReverseGeocodeService.lua.bak.lua	LocationMapView.lua.bak.lua
Command lines.txt			patchluastr.py
LocationDebugPanel.lua.bak.lua

**Comment by astuder** [comment]
looks like you're missing an extra .lua at the end

**Comment by Delfinder** [comment]
Yes, but it does not show in Finder. Can you please provide terminal command to change file name. Sorry, I am now really difficult.

![Untitled](https://user-images.githubusercontent.com/18385567/67307046-1a5bea00-f4b5-11e9-81ea-e880a16e642a.png)

**Comment by astuder** [comment]
Just type the filenames as shown by ls. Finder may dumb down things for the user.

**Comment by Delfinder** [comment]
Managed to change it. Now this is the result:

_Processing LocationMapView.lua.bak
This is not a Lua file._

**Comment by astuder** [comment]
In that case, you got the wrong files. Back to step 4.

**Comment by Delfinder** [comment]
You are correct. It worked now. On Mac do I just replace the file by pasting it, as there is no "replace" command in the menu?

**Comment by Delfinder** [comment]
Sorry, I missed the line under the screenshot. All good. Thank you very much for your wonderful help! Will comment if Map works now.

**Comment by Delfinder** [comment]
It is WORKING!!! **Thank you very much astuder for all your work!**
The only issue is that the map in Lightroom has quite a latency and it shows for a second "Map offline" before it is showing the map.

**Comment by astuder** [comment]
Glad you got it working :)
