### ISSUE TITLE
Map loads quickly, then errors out

### ISSUE THREAD

**Issue by lord-xeon** [astuder/lightroom-map-fix#24]
I'm using Lightroom v6.14, on Windows 10.  I've done all the steps and replaced the `.LUA` and `.lrmodule` files.  When I open up Lightroom and switch to the Map tab I get a quick glance of the map, zoomed in to the area of the selected photo, and I can see markers for other photos in the same folder.  However after a few seconds the screen blinks and the old Oops! Something went wrong. message shows up.

When I log into my Google Cloud API account I see events being logged against the individual APIs so it seems like it's working, but something else is still broken.

I've tried restarting Lightroom many times, I've restarted my computer also, no luck.  Any thoughts help would be greatly appreciated.

**Comment by astuder** [comment]
Did you also activate the GeoCoding API?

**Comment by lord-xeon** [comment]
Yes:
![image](https://user-images.githubusercontent.com/1500115/67512699-62bb0980-f667-11e9-963d-c26692ed3fff.png)

As you can see, there is usage against this key within the last 30 days (I created it 3 days ago).

**Comment by astuder** [comment]
Also review if your payment details in the Google Cloud Console are complete. 

If that's also ok, I don't know what your issue could be.

**Comment by lord-xeon** [comment]
Ah that was it!

I thought that was already set up because I had used this Google Account for other cloud payment things, but I guess they're all separate billing things.

Thanks for your help, and for the project itself, the Map module is one of the big uses I get out of LR and I've been crippled without it lately.
