### ISSUE TITLE
Errors on patchluastr.py

### ISSUE THREAD

**Issue by msmacedo68** [astuder/lightroom-map-fix#26]
Hi people!

I got an error message when trying to use the patchluastr.py script.
I am running on a Mac, MacOS 10.14 Mojave, using Python 3.8.0.

The error message is:
**_('Processing', 'LocationMapView.lua.ORIG')
Traceback (most recent call last):
  File "patchluastr.py", line 69, in <module>
    print("Lua %d.%d detected" % (lua_ver[0] >> 4, lua_ver[0] & 0x0f))
TypeError: unsupported operand type(s) for >>: 'str' and 'int'_**

I tried to comment this line, but the error just moved to the next print instruction. It looks like it is related to incompatible data type, but I really know nothing on Python, so I just don't know how to fix.

Can anybody help, please?
Thanks!

**Comment by astuder** [comment]
Based on the error message, the script is probably executed with Python 2.x. Try running with the command `python3 patchluastr.py...` instead of `python patchluastr.py...`.

**Comment by msmacedo68** [comment]
> Based on the error message, the script is probably executed with Python 2.x. Try running with the command `python3 patchluastr.py...` instead of `python patchluastr.py...`.

Hi Astuder!

Thanks for the ultra quick reply. That was exactly the issue. I never installed python on my Mac. I didn't know that it have python natively...

So glad my map module is back!!!!

Thanks a lot, buddy!
