### ISSUE TITLE
Billing - Free Trial Ending?

### ISSUE THREAD

**Issue by MiTown** [astuder/lightroom-map-fix#28]
The map module in my LR6 has been functioning fine thanks to this excellent mod.  However I’ve started getting emails From Google Cloud Platform saying my Free Trial is coming to an end and advising I upgrade now or I’ll lose resources.  I didn’t even know I was on a free trial. Is this normal? Anyone else encountered this? I don’t want to lose the map module yet again, but If I upgrade would I still get a monthly free credit?

(Apologies in advance if this issue has already been answered (I did look), or if I’ve put this in the wrong place).

**Comment by astuder** [comment]
I've received the same email a few weeks ago and also struggle to understand what it means cost wise - and also wasn't aware that I even was on a free trial. So far I didn't take action and everything still works.

I don't think it will be a problem switching to the regular plan if/when the free trial expires. I.e. I'm taking a wait-and-see approach.

**Comment by vb0** [comment]
Well the other shoe has dropped now, trial expired and the maps is showing (in Lightroom) in the background "For Development Purposes Only" and from time to time giving a "Request Denied" message. It's unclear if "Google Cloud Free Tier" can be used for what we need and otherwise the interface is unbelievably complicated.

**Comment by astuder** [comment]
I don't see that issue on my installation yet. That being said, I don't see anywhere in the Google Cloud Console, that my account would be a trial account.

Did you register a credit card with your Google Cloud account?

**Comment by astuder** [comment]
But I see that my $300 Free Trial credits expired - without having used up any of it.
Billing -> Promotional credits -> Credit details
![Promotional](https://user-images.githubusercontent.com/1166488/78696529-6b6d6800-78b4-11ea-9bbf-189b5329656e.PNG)
![TrialCredit](https://user-images.githubusercontent.com/1166488/78696546-6dcfc200-78b4-11ea-9506-e1ede2dbf647.PNG)

**Comment by vb0** [comment]
Ok I've got it I think, I had a credit card (actually multiple) well set up in GCD but somehow the GCD account wasn't activate after my free credits expired. At some point it gave me a relatively scary message but in the end it looks to be just "pay what you use", to have $200/mo credits so I said yes and now everything works (I set up budget alert and API throttling but it's still annoying that you can't just cap the money to a specific value, I wonder how this will work with a prepay credit card just to be on the safe side):

Upgrade your account
You’re one step away from unlocking all of GoogleCloud Platform.
You won’t be charged until after your free credits run out or expire (whichever comes first). Learn more
You only pay for what you use. View pricing details
