### ISSUE TITLE
Map Is Offline

### ISSUE THREAD

**Issue by DigitalJens** [astuder/lightroom-map-fix#29]
Hello everybody,

at first I want to thank you for providing this great solution! Unfortunately on my side it does not work like expected.

I have done everything like described in the readme.
I took care about my API key. It doesn't contain any special characters.
I'm using Windows 10 and Lightroom 6.14.
I already moved the patched Location.lrmodule file to a different location and started Lightroom afterwards => Map module has been gone. After copying back the file to the original directory and starting Lightroom again, the Map module appears again. But the message Map is Offline is still there. But this shows that I'm working on the right file.

Attached you can find a screenshot of my command line. May it have something to do with the python out of my Anaconda distribution? Or may everything be set up fine but due to a high load on google maps or the google cloud in general caused by the current Corona situation?

![Console](https://user-images.githubusercontent.com/41649441/77249224-e5a8b600-6c3f-11ea-8e39-afd29087d77e.png)

And finally I attached a screenshot out of Lightroom how it looks like. If I remember well, some time ago there has been displayed another error message. But this may have something to do with the upgrade from Windows 7 to 10?!

![Lightroom](https://user-images.githubusercontent.com/41649441/77249335-90b96f80-6c40-11ea-9a51-3759d80bc176.png)

What is kind of suspicous to me is that the change date of the Location.lrmodule file is not changing during the patch process. But since the file size is different to my backup file, the changes must have come into effect.

One more thing: I have no restrictions on the API key and the number of overall API calls is still 0 after all my testing.

Thank you for reading so far! Any help is welcome!

Best regards

Jens

**Comment by DigitalJens** [comment]
Hey guys,

I solved it. Due to other strange behavior when connecting to the internet I found out that accidentially a Proxy has been used in my Windows Proxy settings. After disabling the Proxy it works now.

Best regards!

Jens

**Comment by astuder** [comment]
Happy to hear that you solved the problem and thanks for letting us know 👍
