### ISSUE TITLE
AGREVERSEGEOCODESERVICE.LUA error "This is not a Lua file."

### ISSUE THREAD

**Issue by nupski** [astuder/lightroom-map-fix#32]
Hi Adrian,

I've been following your instructions but while the LOCATIONMAPVIEW.LUA file works fine and the API key gets changed but AGREVERSEGEOCODESERVICE.LUA gives me a "This is not a Lua file." error message.

I tried this with Python3 on Linux and with the Windows exe with the same result.

I've uploaded a zip of the Location.lrmodule file in case you need it for debug.

[removed attachment]

Any ideas?

Cheers, Dylan.

System details:
Lightroom version: 6.14 [ 1149743 ]
License: Perpetual
Language setting: en
Operating system: Windows 10 - Business Edition
Version: 10.0.18363
Application architecture: x64
System architecture: x64
Logical processor count: 4
Processor speed: 2.5 GHz
Built-in memory: 16079.7 MB

**Comment by astuder** [comment]
I did a diff between my version of AGREVERSEGEOCODESERVICE.LUA and the file extracted with Resource Hacker from your Location.lrmodule, and they are identical.

Maybe try to extract it again? Make sure to use the right option (Save *.bin resource)

**Comment by nupski** [comment]
Hi Adrian,

Yup, I worked out what I was doing wrong. My input and output filenames were the same... Numpty mistake. I just need to rebuild the Location.lrmodule and get it back where it needs to be.

Sorry for wasting your time!

Cheers,

Dylan.

**Comment by astuder** [comment]
No worries.
