### ISSUE TITLE
Documentation of .patch files

### ISSUE THREAD

**Issue by pbb72** [astuder/lightroom-map-fix#33]
The documentation doesn't explain where to find the .patch files that are referenced in the code examples. If someone follows the instructions line for line, they will get an error here, because they haven't downloaded these files.

While it is relatively obvious where the files are, skipping this information is in contrast to the very detailed instructions for the rest.

Also, there is an error. The code example for the StreetView hack uses the OSM patch file.

**Comment by astuder** [comment]
Thanks
