### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ccoenen** [astuder/lightroom-map-fix#35]
Thanks to this, I now have a fully working LR6 once again :-)
![grafik](https://user-images.githubusercontent.com/124909/89840535-beac3b80-db70-11ea-97d3-66e2e9851c1f.png)

**Comment by ccoenen** [comment]
(insta-close to not litter the bugtracker; i hope you got the notification, though :-) )

**Comment by astuder** [comment]
you're welcome :)
