### ISSUE TITLE
How to see Javascript console?

### ISSUE THREAD

**Issue by bwims** [astuder/lightroom-map-fix#36]
Hi everyone!  All attempts to google how to see the JS console only return the maps issue.

However, I am having trouble getting the patches working and it would be very helpful to see the console messages, like I can see in the screenshots here.

What is the magic incantation, please?

Thanks!

Brian

**Comment by bwims** [comment]
Whoops!  I just noticed that it was a patch option.  This implies that, despite lightroom having a message to "see the Javascript Console"  Adobe does not provide the ability to do so!  How braindead!

**Comment by astuder** [comment]
If you are running Windows 10, maybe you are encountering this problem:
https://github.com/astuder/lightroom-map-fix/issues/21#issuecomment-546711535
Make sure to change the extension of your backup file to something else than .lrmodule.
