### ISSUE TITLE
Works but with "For Development Purposes Only" overlay on darkened map

### ISSUE THREAD

**Issue by jimwjimw** [astuder/lightroom-map-fix#40]
"For Development Purposes Only" overlay appears on the darkened main map and on mini Navigation map.  The Nav map has the corner of a web error message "This page can't load Goo..." and a link is just clickable labeled "do you own this website" which takes me to this page: https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors

Unfortunately I cant seem to find anything obvious wrong. Billing looks OK and I copied and pasted the API key, so doubt it's incorrect.

The credentials page seems to want me to do something with OAuth consent, but I am out of my depth here (I'm a photographer with limited web experience), and I'm not even sure OAuth important/what it does/if I need it.

Other that that, map seems to work fine! Thanks!!

**Comment by astuder** [comment]
Can you share a screenshot of your issue? I just started up Lightroom and I don't see an error message.

Given the link to billing makes me suspect that there's an issue with your account or billing configuration. Not sure about the OAuth thing, maybe it requires you to use two-factor authentication for the Google account you used to setup Google Cloud.

**Comment by jimwjimw** [comment]
Well, how bizarre.  I had to restart LR as I was running out of memory to do something else, and as if by magic, this time, the error has disappeared…

I had re-started it after replacing the components, but seemingly it needed another restart to work correctly. 

Oh well, sorry to waste your time.  And thanks again!

-Jim



On Sep 8, 2022, at 1:41 PM, Adrian Studer ***@***.***> wrote:


Can you share a screenshot of your issue? I just started up Lightroom and I don't see an error message.

Given the link to billing makes me suspect that there's an issue with your account or billing configuration. Not sure about the OAuth thing, maybe it requires you to use two-factor authentication for the Google account you used to setup Google Cloud.
