### ISSUE TITLE
client=gme-adobesystems not found

### ISSUE THREAD

**Issue by NemethR84** [astuder/lightroom-map-fix#43]
Dear All,

While trying to make this work, I get the below error for the files:
 LOCATIONMAPVIEW.LUA
 AGREVERSEGEOCODESERVICE.LUA

Other commands seem to work, so it seems to me, that maybe this (original) line changed to something else?

patchluastr.exe AGREVERSEGEOCODESERVICE.LUA "client=gme-adobesystems" "key=XXXXXXXXXXXXXXXXXX" -o AGREVERSEGEOCODESERVICE.bin
Reading AGREVERSEGEOCODESERVICE.LUA
Lua 5.1 detected
Lua settings: endian 1, int 4, size_t 8, instruction 4, number 8
16498 bytes read from file
'client=gme-adobesystems' not found, nothing to patch
16498 bytes written to AGREVERSEGEOCODESERVICE.bin

**Comment by astuder** [comment]
Is this with a "pristine" Lightroom installation, or was it previously patched, and you're trying to make it work again?

**Comment by NemethR84** [comment]
Hello.

Thank you for the quick reply.
This is the first time I try to run this "fix", so i would say, it is a pristine installation.
Lightroom 12.3

**Comment by astuder** [comment]
Are you sure about your version of Lightroom? This method of enabling maps is for pre-subscription Lightroom, typically of version 6.x. 

Can you post the version shown in Help > System Information?

**Comment by NemethR84** [comment]
My bad.

**Comment by astuder** [comment]
no worries :)
