### ISSUE TITLE
No luck

### ISSUE THREAD

**Issue by Adrmr** [astuder/lightroom-map-fix#5]
Sadly, I seem to be the only one having trouble getting it to work (LR6.14 and Win 10).
As far as I can tell, I have followed the instructions. At least, I can't figure what I'm doing wrong. :-(

Google account is set up.
The 2 permissions are set for my new project.
I use my own key.
location.lrmodule is patched from the modified .lua files.

All I get is the map flashing up for a split second when I first enter the Map Module, then only the usual error message.

I see no access or error logged in the Google Cloud console, which is worrying..
(Interestingly, Lightroom does not complain if I delete location.lrmodule as a test, but perhaps that is normal behavior?)

**Comment by astuder** [comment]
If you can delete (or safer, rename) location.lrmodule and nothing changes, it's very likely that the Lightroom you are running is installed in a different location. Also make sure to exit Lightroom before modifying location.lrmodule.

**Comment by Adrmr** [comment]
Now I'm really puzzled.

I have scanned my drives for possible alternate installations of LR6 and/or alternated copies of the various .LRMODULE files. Nothing, except for what in LR5's installation directory, and I have renamed that, just to be sure.

I start LR6 by clicking the .EXE in the appropriate installation folder, i.e. the one that also contains the LOCATION.LRMODULE I patch.
I also shut LR down between every change I make.

This is what's puzzling: As a test I have now renamed most of the .lrmodule files that seem important, e.g. BOOK., DEVELOP., EXPORT., IMPORT., LAYOUT., LIBRARY. and LOCATION.
LR6 works as normal, as if nothing is missing.

It's almost as if it doesn't read those files at all...?
Any thoughts?

**Comment by Adrmr** [comment]
And now it works.

Making the Location.lrmodule unavailable to LR, closing LR, then copying Location.lrmodule back, and starting LR again has made it work as expected.

I'm clueless as to why, but maybe this will help someone else.

**Comment by astuder** [comment]
Thanks for reporting back. LR may have had the file locked and Windows for some reason didn't tell you that you weren't allowed to overwrite it with the patched version.

Re GeoCoding, see issue #3

**Comment by astuder** [comment]
Though, the address search box works for me without what's described in the other issue. If the search box is your problem, make sure Geocode API is enabled in your Google Cloud Console and that you patched AgReverseGecodeService.lua as per documentation.
