### ISSUE TITLE
LR 5 can't get to work

### ISSUE THREAD

**Issue by vonGameTheory** [astuder/lightroom-map-fix#8]
Anybody gotten this to work on LR5?  (v5.7.1)  It still gives the same "Map view is no longer supported on this version of Lightroom" error and then "map is offline" with forever spinning wheel.  If I capture the traffic, I can see it shooting a Google request with my API key that seems successful, but the Adobe error actually comes before that occurs, so it seems like this version just isn't going to try and that's that.

**Comment by astuder** [comment]
What is the URL sent to Google (with your API key removed/hidden)?

**Comment by vonGameTheory** [comment]
When you hit the Map tab, it shoots one request to:

http://www.photoshop.com/api/service_status/lightroom/5.7:v1.0.0.0/win/en_us/google-map.json

and another to:

https://maps-api-ssl.google.com/maps/api/js?v=3.9&key={my_api_key_here}&sensor=false&callback=initialize&language=EN&region=EN&channel=lightroom-5.7&signature={some_signature_here}

(I don't know what the signature is, removed in case it compromises my API in some way)

The Google request succeeds and returns some sort of javascript map library.  The photoshop request re-directs to an https version of the same url and returns:

{
  "locale": "en_us",
  "status": "kill",
  "message_title": "Map is not available",
  "message_body": "Map view is no longer supported on this version of Lightroom.  For more information go to www.adobe.com/go/lightroom-map",
  "timestamp": "2018-07-16T06:33:49Z"
}

Which is the error displayed in a pop-up box back in Lightroom 5.  Dismiss the box and it leaves "map is offline" over an unusable map forever -- no more requests are made.

**Comment by vonGameTheory** [comment]
I'm not sure what I'm supposed to try exactly -- I'm supposed to hack the python script to change other things?  

But just again, there is no error from google -- it returns a large javascript library.   (I can post it if you want.)   But as soon as it gets that kill message back from photoshop that's it, the map is dead, unclickable, nothing displayed, no more requests.

I will put the original back and see what the traffic is doing -- didn't check it before I swapped them.

**Comment by astuder** [comment]
I don't have LR5, so I'm just guessing blindly :-) 

No need to change `patchluastr.py`. Simply provide the string that needs to be modified and the replacement string.

If you think the call to photoshop.com is to blame, you could try to find that URL in a LUA file and then modify it using patchluastr. For example replacing the 5.7 in that URL with 8.1 gives this response:
```
locale: "en_us"
status: "ok"
timestamp: "2019-01-28T00:14:28+00:00"
```

**Comment by vonGameTheory** [comment]
Right, make it so it doesn't get an error.  Duh, I'll try that.  I might also be able to man-in-the-middle it with Fiddler and play around with responses.  I will report back.

**Comment by astuder** [comment]
If we're lucky, it can process `file:///C:/...` style URLs and you could replace the photoshop.com call with a local JSON file.

**Comment by vonGameTheory** [comment]
So just to update this, I was able to supress the pop-up error msg by replacing the response with a status "ok" as suggested above (I did this with Fiddler), but that's as far as I got.  It did make another (successful) call to the server after that (for more js scripts), but the map still did nothing.  And then I ended up getting the CC plan recently anyway, so that's as far as I'm going to take it with LR5.

**Comment by thefool** [comment]
any progress on this? can I help? I could send you the original files for you to have a look at. 

concerning the photoshop.com call, how about just replacing the version number in the URL?
this URL returns a better looking json: 
[https://www.photoshop.com/api/service_status/lightroom/8.0:v1.0.0.0/win/en_us/google-map.json](https://www.photoshop.com/api/service_status/lightroom/8.0:v1.0.0.0/win/en_us/google-map.json)

**Comment by astuder** [comment]
I doubt that you will find the version number as replaceable string. But I noticed that the service will return OK if you modify the name of the .json file to something it doesn't know. E.g. google-map.json -> goggle-map.json

**Comment by B-G-T** [comment]
Any update on this? What is the blocking point?

**Comment by vonGameTheory** [comment]
As I said earlier, I was able to suppress some of the error messages, but never was able to get the map to work again on LR5.
