### ISSUE TITLE
Error running script - LR 6.14 on Mac

### ISSUE THREAD

**Issue by giudasvelto** [astuder/lightroom-map-fix#9]
I'm on a Mac with LR 6.14 and I'm having an issue while running patchluastr.py, specifically on line 69:
"TypeError: unsupported operand type(s) for >>: 'str' and 'int'
I tried to opt out the line but then I get the error that LUA version is not compatible with PUC-Rio.
I'm actually on a subscription, but I have an older OS and I can't upgrade LR. Is it possible my lua version is different from the other Mac users'?
Any help is greatly appreciated, thanks.

**Comment by astuder** [comment]
That line just outputs what it read from the file, so commenting it out doesn't really change anything. 

What version of Python do you have installed? The script was developed with a fairly recent installation of Python 3 and may not work with Python 2.7.

I you email me the Lua file (see my profile page for the address) I can give it a try on my system.

**Comment by giudasvelto** [comment]
I upgraded Python just before trying the code, so I have version 3.7 installed.
Anyway I emailed you the files. if you can have a look at them, that'd be great.
Thanks!

**Comment by maxwimmer** [comment]
I had exactly the same error message. Although I did install Python 3.7, I realized that there was also an old Python 2 installation on my Mac that was called by default. Calling "python3 patchluastr.py ..." in terminal solved it.

**Comment by MiTown** [comment]
Worked for me too! Fabulous.
Thank you for the guidance.

**Comment by astuder** [comment]
Thanks everyone!

I updated the README with the workaround.
